"""CadQuery starter backend: local, deterministic mechanical-plate generation.

Optional: only usable if the `cadquery` package is already importable in
this environment (see factory.cad.backend.is_cadquery_available). This
module never installs cadquery, never imports/executes the CadQuery source
it writes, never invokes a slicer, and never contacts a printer or network -
STL export is always a manual, human-run step, exactly like the existing
OpenSCAD generator (factory.openscad.generate). See docs/cad-backends.md.
"""

from __future__ import annotations

from pathlib import Path

from factory import project_store
from factory.cad.backend import GeneratedCadResult, is_cadquery_available
from factory.cad.manifest import upsert_cadquery_manifest_entry

ALLOWED_TEMPLATES = ("mechanical-plate",)
EXPORT_INSTRUCTIONS_FILENAME = "cadquery_export_instructions.md"


class CadQueryNotAvailableError(Exception):
    pass


class ProjectNotInitializedError(Exception):
    pass


class GeneratedFileExistsError(Exception):
    def __init__(self, conflicts: list[Path]):
        self.conflicts = conflicts
        joined = ", ".join(str(p) for p in conflicts)
        super().__init__(f"refusing to overwrite existing file(s) without --force: {joined}")


def _require_initialized_project(project_dir: Path) -> None:
    required = ("cad", "stl", "slicer_review")
    missing = [sub for sub in required if not (project_dir / sub).is_dir()]
    if missing or not (project_dir / "part_manifest.json").is_file():
        raise ProjectNotInitializedError(
            f"{project_dir} does not look like an initialized factory project "
            f"(missing: {missing or ['part_manifest.json']}). Run `factory init-project` first."
        )


def _mechanical_plate_source(
    length_mm: float,
    width_mm: float,
    thickness_mm: float,
    corner_radius_mm: float,
    hole_diameter_mm: float | None,
    hole_margin_mm: float,
    label_text: str | None,
    label_size_mm: float,
) -> str:
    """Return CadQuery Python source text. Never executed here - a human runs it."""
    lines = [
        "# mechanical_plate.py",
        "# Parametric rectangular mechanical plate generated by ai-3d-factory",
        "# (factory generate-cadquery --template mechanical-plate).",
        "# Run this script yourself (python cad/mechanical_plate.py) to export",
        "# stl/mechanical_plate.stl - ai-3d-factory never invokes CadQuery automatically.",
        "# Geometry sanity check passed does not mean print-ready - human slicer",
        "# review is still required. See AGENT.md.",
        "",
        "import cadquery as cq",
        "from pathlib import Path",
        "",
        "# ---- Parameters (all in millimeters) ----",
        f"length_mm = {length_mm!r}",
        f"width_mm = {width_mm!r}",
        f"thickness_mm = {thickness_mm!r}",
        f"corner_radius_mm = {corner_radius_mm!r}  # set to 0 for square corners",
        f"hole_diameter_mm = {hole_diameter_mm!r}  # set to a number to add 4 corner mounting holes",
        f"hole_margin_mm = {hole_margin_mm!r}  # distance of hole centers from each edge",
        f"label_text = {label_text!r}  # set to a short string to engrave centered on the top face",
        f"label_size_mm = {label_size_mm!r}",
        "",
        "plate = cq.Workplane(\"XY\").box(length_mm, width_mm, thickness_mm)",
        "if corner_radius_mm:",
        "    plate = plate.edges(\"|Z\").fillet(corner_radius_mm)",
        "",
        "if hole_diameter_mm:",
        "    plate = (",
        "        plate.faces(\">Z\")",
        "        .workplane()",
        "        .rect(length_mm - 2 * hole_margin_mm, width_mm - 2 * hole_margin_mm, forConstruction=True)",
        "        .vertices()",
        "        .hole(hole_diameter_mm)",
        "    )",
        "",
        "if label_text:",
        "    plate = (",
        "        plate.faces(\">Z\")",
        "        .workplane()",
        "        .text(label_text, label_size_mm, -0.6, cut=True, halign=\"center\", valign=\"center\")",
        "    )",
        "",
        'if __name__ == "__main__":',
        "    output_path = Path(__file__).resolve().parent.parent / \"stl\" / \"mechanical_plate.stl\"",
        "    output_path.parent.mkdir(parents=True, exist_ok=True)",
        "    cq.exporters.export(plate, str(output_path))",
        '    print(f"Exported {output_path}")',
        "",
    ]
    return "\n".join(lines)


def _write_export_instructions(project_dir: Path) -> Path:
    cad_dir = project_dir / "cad"
    py_files = sorted(p.name for p in cad_dir.glob("*.py"))

    lines = [
        "# CadQuery export instructions",
        "",
        "This file lists the local commands to export each generated CadQuery (.py) script",
        "to an STL. **Nothing in this repo runs these commands automatically.** Run them",
        "yourself, in a terminal, only after you've reviewed the source. This requires",
        "CadQuery to be installed locally in your Python environment.",
        "",
        "```bash",
    ]
    for name in py_files:
        lines.append(f"python cad/{name}")
    lines.append("```")
    lines.append("")
    lines.append(
        "Each script exports its own STL directly (see the `if __name__ == \"__main__\":` block "
        "at the bottom of the script) - there is no separate export command."
    )
    lines.append("")
    lines.append(
        "After exporting, run `factory validate stl/<name>.stl` and `factory render "
        "stl/<name>.stl` on each exported file, then update `part_manifest.json` with the "
        "real material/color choices before requesting human slicer review. See "
        "`docs/slicer-review-workflow.md`."
    )
    lines.append("")
    lines.append(
        "This repo never slices, prints, or uploads anything - exporting to STL is the last "
        "step this documentation covers."
    )
    lines.append("")

    out_path = project_dir / "slicer_review" / EXPORT_INSTRUCTIONS_FILENAME
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def generate_cadquery(
    project_dir: Path,
    template: str,
    *,
    length_mm: float = 80.0,
    width_mm: float = 50.0,
    thickness_mm: float = 5.0,
    corner_radius_mm: float = 4.0,
    hole_diameter_mm: float | None = None,
    hole_margin_mm: float = 8.0,
    label_text: str | None = None,
    label_size_mm: float = 8.0,
    force: bool = False,
) -> GeneratedCadResult:
    """Generate local CadQuery source into <project_dir>/cad/. Never invokes CadQuery,
    never exports an STL, never touches a network or a printer."""
    if template not in ALLOWED_TEMPLATES:
        raise ValueError(f"Unknown template {template!r}. Allowed: {', '.join(ALLOWED_TEMPLATES)}")

    project_dir = Path(project_dir)
    _require_initialized_project(project_dir)

    if not is_cadquery_available():
        raise CadQueryNotAvailableError(
            "CadQuery is not installed or not available in this environment.\nNo files were generated."
        )

    source = _mechanical_plate_source(
        length_mm=length_mm,
        width_mm=width_mm,
        thickness_mm=thickness_mm,
        corner_radius_mm=corner_radius_mm,
        hole_diameter_mm=hole_diameter_mm,
        hole_margin_mm=hole_margin_mm,
        label_text=label_text,
        label_size_mm=label_size_mm,
    )

    cad_path = project_dir / "cad" / "mechanical_plate.py"
    if cad_path.exists() and not force:
        raise GeneratedFileExistsError([cad_path])

    cad_path.write_text(source, encoding="utf-8")
    export_instructions_path = _write_export_instructions(project_dir)

    stl_path = project_dir / "stl" / "mechanical_plate.stl"
    upsert_cadquery_manifest_entry(
        project_dir,
        part_name="mechanical_plate",
        cad_source="cad/mechanical_plate.py",
        expected_stl_path="stl/mechanical_plate.stl",
        role="mechanical_plate",
        template=template,
    )

    brief_path = project_dir / "brief.json"
    if brief_path.is_file():
        brief = project_store.load_json(brief_path)
        if project_store.advance_status(brief, "cad_generated"):
            project_store.save_json(brief_path, brief)

    return GeneratedCadResult(
        backend_id="cadquery",
        template=template,
        project_dir=project_dir,
        source_files=(cad_path,),
        expected_mesh_files=(stl_path,),
        warnings=(),
        human_actions_required=(
            f"Manually run `python cad/mechanical_plate.py` to export {stl_path} - see "
            f"slicer_review/{EXPORT_INSTRUCTIONS_FILENAME}.",
            "Update part_manifest.json with the real material/color choice before requesting "
            "human slicer review.",
        ),
        safety_notes=(
            "This wrote local CadQuery source and instructions only - it did not run CadQuery, "
            "export an STL, or contact any printer/network/API.",
        ),
    )
