"""Local, deterministic OpenSCAD source generation. No network, no subprocess.

Every function here returns plain text - it never writes files itself and
never invokes OpenSCAD. See factory/openscad/generate.py for the
orchestration that writes these into a project and factory/cli.py for the
`generate-openscad` command.
"""

from __future__ import annotations

from dataclasses import dataclass

ALLOWED_TEMPLATES = ("test-cube", "nameplate", "sign", "multipart-nameplate")

TEMPLATES_REQUIRING_TEXT = ("nameplate", "sign", "multipart-nameplate")


@dataclass(frozen=True)
class GeneratedFile:
    filename: str
    content: str


@dataclass(frozen=True)
class GeneratedPart:
    part_name: str
    cad_filename: str
    role: str
    material_hint: str
    color_hint: str
    transform_notes: str


@dataclass(frozen=True)
class TemplateOutput:
    template: str
    files: tuple[GeneratedFile, ...]
    parts: tuple[GeneratedPart, ...]


def _escape_scad_string(value: str) -> str:
    """Escape a string for safe embedding inside an OpenSCAD double-quoted literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_test_cube() -> TemplateOutput:
    content = '''// test_cube.scad
// Simple calibration/test cube generated by ai-3d-factory
// (factory generate-openscad --template test-cube).
// Purpose: a quick print to sanity-check first-layer adhesion, dimensional
// accuracy, and this project's validate/render pipeline. Not a product design.
// Geometry sanity check passed does not mean print-ready - human slicer
// review is still required. See AGENT.md.

// ---- Parameters (all in millimeters) ----
cube_size = 20;          // edge length of the main cube
corner_marker = true;    // cut a small notch in one top corner to mark orientation
marker_size = 3;         // edge length of the corner notch cube

module test_cube() {
    difference() {
        cube([cube_size, cube_size, cube_size]);
        if (corner_marker) {
            translate([cube_size - marker_size, cube_size - marker_size, cube_size - marker_size])
                cube([marker_size, marker_size, marker_size]);
        }
    }
}

test_cube();
'''
    return TemplateOutput(
        template="test-cube",
        files=(GeneratedFile("test_cube.scad", content),),
        parts=(
            GeneratedPart(
                part_name="test_cube",
                cad_filename="test_cube.scad",
                role="calibration",
                material_hint="any",
                color_hint="any",
                transform_notes="Single part, no alignment with other parts needed.",
            ),
        ),
    )


def render_nameplate(text: str) -> TemplateOutput:
    safe_text = _escape_scad_string(text)
    content = f'''// nameplate.scad
// Raised-text nameplate generated by ai-3d-factory
// (factory generate-openscad --template nameplate).
// Single-color design: base plate and raised text are fused into one solid.
// For a multi-color version with separate aligned parts, use
// --template multipart-nameplate instead.

// ---- Parameters (all in millimeters) ----
plate_width = 90;
plate_depth = 30;
plate_height = 5;
text_string = "{safe_text}";
text_size = 10;
text_height = 2;      // how far the raised text rises above the plate surface
text_font = "Liberation Sans:style=Bold";  // change if this font isn't installed locally

module nameplate_base() {{
    cube([plate_width, plate_depth, plate_height]);
}}

module nameplate_text() {{
    translate([plate_width / 2, plate_depth / 2, plate_height])
        linear_extrude(height = text_height)
            text(text_string, size = text_size, halign = "center", valign = "center", font = text_font);
}}

union() {{
    nameplate_base();
    nameplate_text();
}}
'''
    return TemplateOutput(
        template="nameplate",
        files=(GeneratedFile("nameplate.scad", content),),
        parts=(
            GeneratedPart(
                part_name="nameplate",
                cad_filename="nameplate.scad",
                role="nameplate",
                material_hint="any",
                color_hint="single color (base and text fused)",
                transform_notes="Single fused part, no multi-part alignment needed.",
            ),
        ),
    )


def render_sign(text: str) -> TemplateOutput:
    safe_text = _escape_scad_string(text)
    content = f'''// sign.scad
// Simple rectangular sign/plate with raised text, generated by ai-3d-factory
// (factory generate-openscad --template sign).
// Single-color design: plate and text are fused into one solid.

// ---- Parameters (all in millimeters) ----
plate_width = 150;
plate_depth = 50;
plate_height = 4;
text_string = "{safe_text}";
text_size = 16;
text_height = 1.6;    // how far the raised text rises above the plate surface
text_font = "Liberation Sans:style=Bold";  // change if this font isn't installed locally

module sign_plate() {{
    cube([plate_width, plate_depth, plate_height]);
}}

module sign_text() {{
    translate([plate_width / 2, plate_depth / 2, plate_height])
        linear_extrude(height = text_height)
            text(text_string, size = text_size, halign = "center", valign = "center", font = text_font);
}}

union() {{
    sign_plate();
    sign_text();
}}
'''
    return TemplateOutput(
        template="sign",
        files=(GeneratedFile("sign.scad", content),),
        parts=(
            GeneratedPart(
                part_name="sign",
                cad_filename="sign.scad",
                role="sign",
                material_hint="any",
                color_hint="single color (plate and text fused)",
                transform_notes="Single fused part, no multi-part alignment needed.",
            ),
        ),
    )


def render_multipart_nameplate(text: str) -> TemplateOutput:
    safe_text = _escape_scad_string(text)

    base_content = '''// nameplate_base.scad
// Base plate for a multi-color raised-text nameplate (aligned part 1 of 2).
// Generated by ai-3d-factory (factory generate-openscad --template multipart-nameplate).
// Export this and nameplate_text.scad to separate STLs and import both into
// your slicer as separate aligned parts sharing this same origin - do not
// re-center either part. See docs/slicer-review-workflow.md.

// ---- Shared parameters (all in millimeters) - keep in sync with nameplate_text.scad ----
plate_width = 90;
plate_depth = 30;
plate_height = 5;

module nameplate_base() {
    cube([plate_width, plate_depth, plate_height]);
}

nameplate_base();
'''

    text_content = f'''// nameplate_text.scad
// Raised text for a multi-color raised-text nameplate (aligned part 2 of 2).
// Generated by ai-3d-factory (factory generate-openscad --template multipart-nameplate).
// Shares the same origin as nameplate_base.scad - do not re-center this part.
// See docs/slicer-review-workflow.md.

// ---- Shared parameters (all in millimeters) - keep in sync with nameplate_base.scad ----
plate_width = 90;
plate_depth = 30;
plate_height = 5;
text_string = "{safe_text}";
text_size = 10;
text_height = 2;      // how far the raised text rises above the plate surface
text_font = "Liberation Sans:style=Bold";  // change if this font isn't installed locally

module nameplate_text() {{
    translate([plate_width / 2, plate_depth / 2, plate_height])
        linear_extrude(height = text_height)
            text(text_string, size = text_size, halign = "center", valign = "center", font = text_font);
}}

nameplate_text();
'''

    shared_origin_note = (
        "Shared origin with nameplate_base.scad/nameplate_text.scad: both parts are "
        "modeled from the same (0,0,0) corner and must be imported into the slicer "
        "without re-centering either one."
    )

    return TemplateOutput(
        template="multipart-nameplate",
        files=(
            GeneratedFile("nameplate_base.scad", base_content),
            GeneratedFile("nameplate_text.scad", text_content),
        ),
        parts=(
            GeneratedPart(
                part_name="nameplate_base",
                cad_filename="nameplate_base.scad",
                role="base_plate",
                material_hint="TBD - choose base color/material",
                color_hint="TBD - base color",
                transform_notes=shared_origin_note,
            ),
            GeneratedPart(
                part_name="nameplate_text",
                cad_filename="nameplate_text.scad",
                role="raised_letters",
                material_hint="TBD - choose contrasting text color/material",
                color_hint="TBD - contrasting text color",
                transform_notes=shared_origin_note,
            ),
        ),
    )


_RENDERERS = {
    "test-cube": lambda text: render_test_cube(),
    "nameplate": lambda text: render_nameplate(text),
    "sign": lambda text: render_sign(text),
    "multipart-nameplate": lambda text: render_multipart_nameplate(text),
}


def render_template(template: str, text: str | None) -> TemplateOutput:
    if template not in ALLOWED_TEMPLATES:
        raise ValueError(f"Unknown template {template!r}. Allowed: {', '.join(ALLOWED_TEMPLATES)}")

    if template in TEMPLATES_REQUIRING_TEXT and not text:
        raise ValueError(f"Template {template!r} requires --text.")

    return _RENDERERS[template](text)
