// mechanical_plate.scad
// Hand-authored parametric rectangular mounting plate example for the
// ai-3d-factory examples/ library (examples/mechanical-plate/).
//
// Not generated by `factory generate-openscad` - no built-in OpenSCAD
// template covers a rounded-corner plate with mounting holes yet (the
// built-in templates are test-cube/nameplate/sign/multipart-nameplate,
// see factory/openscad/templates.py). Parameter names deliberately mirror
// `factory generate-cadquery --template mechanical-plate`
// (factory/cad/cadquery_backend.py) so the two backends stay easy to
// compare; CadQuery is an optional dependency not installed in this
// environment, so this example uses OpenSCAD, the backend that's actually
// usable here. See docs/cad-backends.md.
//
// This repo does not run OpenSCAD automatically. Geometry sanity check
// passed does not mean print-ready - human slicer review is still
// required. See AGENT.md.

// ---- Parameters (all in millimeters) ----
length_mm = 80;
width_mm = 50;
thickness_mm = 5;
corner_radius_mm = 4;    // set to 0 for square corners
hole_diameter_mm = 4;    // set to 0 to omit the 4 corner mounting holes
hole_margin_mm = 8;      // distance of hole centers from each edge

module plate_outline() {
    if (corner_radius_mm > 0) {
        hull() {
            for (x = [corner_radius_mm, length_mm - corner_radius_mm])
                for (y = [corner_radius_mm, width_mm - corner_radius_mm])
                    translate([x, y, 0])
                        cylinder(r = corner_radius_mm, h = thickness_mm, $fn = 32);
        }
    } else {
        cube([length_mm, width_mm, thickness_mm]);
    }
}

module mounting_holes() {
    for (x = [hole_margin_mm, length_mm - hole_margin_mm])
        for (y = [hole_margin_mm, width_mm - hole_margin_mm])
            translate([x, y, -1])
                cylinder(d = hole_diameter_mm, h = thickness_mm + 2, $fn = 32);
}

difference() {
    plate_outline();
    if (hole_diameter_mm > 0) {
        mounting_holes();
    }
}
