"""Phase 47A: Meshy transport abstraction + mocked implementation.

**This module never contacts a network.** `MeshyTransport` defines the
three operations a real transport would eventually need
(`submit_task()`/`get_task()`/`download_artifact()`); `MockMeshyTransport`
is the only implementation that exists in this repo. There is
deliberately no `HttpMeshyTransport`, not even a non-functional skeleton -
see the Phase 47A spec's "Transport abstraction" section ("Preferred: do
not implement live transport at all in 47A"). A future Phase 47B would
add a real transport as a *separate*, *separately-approved* class; this
module does not anticipate its shape beyond the interface below.

`MockMeshyTransport` reads fixed, checked-in JSON fixtures from
`tests/fixtures/meshy/` (mirroring the response shapes
`docs/meshy-current-research.md` documented) and a fixed local STL
fixture (`tests/fixtures/meshy/mock_concept.stl`) - never anything
downloaded, generated by a live tool, or derived from real Meshy output.
Every mock task id is prefixed `mock-meshy-` so it can never be confused
with (or logged/printed as though it were) a real Meshy task id.
"""

from __future__ import annotations

import copy
import shutil
import uuid
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

from factory import project_store

FIXTURES_DIR = project_store.REPO_ROOT / "tests" / "fixtures" / "meshy"

# The mocked lifecycle scenarios this transport can simulate - see the
# Phase 47A spec's "Mock transport" section. Each name maps directly to
# one of the fixture files below (plus "success", which chains three:
# submit -> processing -> success).
MOCK_SCENARIOS = ("success", "failure", "rate_limited", "server_error", "expired_artifact")

_FIXTURE_FILES = {
    "submit": "text_to_3d_submit_success.json",
    "processing": "text_to_3d_processing.json",
    "success": "text_to_3d_success.json",
    "failure": "text_to_3d_failure.json",
    "expired_artifact": "expired_artifact.json",
    "rate_limit_error": "rate_limit_error.json",
    "server_error": "server_error.json",
}


class MeshyTransportError(Exception):
    """Raised by a transport for a structured, expected failure - callers
    (see `factory.meshy_adapter`) catch this and translate it into one of
    `factory.meshy_models.ERROR_CODES`, never letting it escape as a bare
    traceback into a CLI result."""

    def __init__(self, error_code: str, message: str, *, retry_allowed: bool = False):
        super().__init__(message)
        self.error_code = error_code
        self.message = message
        self.retry_allowed = retry_allowed


def _load_fixture(name: str) -> dict[str, Any]:
    path = FIXTURES_DIR / _FIXTURE_FILES[name]
    return project_store.load_json(path)


class MeshyTransport(ABC):
    """The transport interface a future real implementation would satisfy.
    Never imported/implemented with a real HTTP client in this phase."""

    @abstractmethod
    def submit_task(self, request: dict[str, Any]) -> dict[str, Any]: ...

    @abstractmethod
    def get_task(self, task_id: str) -> dict[str, Any]: ...

    @abstractmethod
    def download_artifact(self, model_url: str, destination: Path) -> Path: ...


class MockMeshyTransport(MeshyTransport):
    """Deterministic, offline, fixture-driven transport. No network
    import is used anywhere in this class or module (see
    `tests/test_meshy_adapter_safety.py`'s import/AST scan)."""

    def __init__(self, scenario: str = "success"):
        if scenario not in MOCK_SCENARIOS:
            raise ValueError(f"scenario {scenario!r} is not one of {MOCK_SCENARIOS!r}")
        self.scenario = scenario
        self._poll_count = 0
        self._task_id: str | None = None

    def submit_task(self, request: dict[str, Any]) -> dict[str, Any]:
        if self.scenario == "rate_limited":
            advisory = _load_fixture("rate_limit_error")
            raise MeshyTransportError("rate_limited", advisory["message"], retry_allowed=advisory["retry_allowed"])
        if self.scenario == "server_error":
            advisory = _load_fixture("server_error")
            raise MeshyTransportError("server_error", advisory["message"], retry_allowed=advisory["retry_allowed"])

        self._task_id = f"mock-meshy-{uuid.uuid4()}"
        response = copy.deepcopy(_load_fixture("submit"))
        response["id"] = self._task_id
        response.pop("_mock_note", None)
        response["type"] = request.get("request_type", "text_to_3d").replace("_", "-")
        return response

    def get_task(self, task_id: str) -> dict[str, Any]:
        """Advances a simple, deterministic step counter each call to
        simulate polling - never sleeps, never makes a real request. The
        step sequence per scenario mirrors
        docs/meshy-current-research.md's documented `status` values."""
        self._poll_count += 1

        if self.scenario == "success":
            fixture_name = "processing" if self._poll_count == 1 else "success"
        elif self.scenario == "failure":
            fixture_name = "processing" if self._poll_count == 1 else "failure"
        elif self.scenario == "expired_artifact":
            fixture_name = "processing" if self._poll_count == 1 else "expired_artifact"
        else:
            fixture_name = "processing"

        response = copy.deepcopy(_load_fixture(fixture_name))
        response["id"] = task_id
        response.pop("_mock_note", None)
        return response

    def download_artifact(self, model_url: str, destination: Path) -> Path:
        """Never downloads anything - copies the one fixed, checked-in
        local STL fixture. `model_url` (a fake `mock://...` URL from the
        fixture response) is accepted only to match the transport
        interface's real shape; it is never opened, resolved, or
        contacted."""
        if self.scenario in ("failure", "rate_limited", "server_error"):
            raise MeshyTransportError("artifact_missing", "No artifact exists for a task that did not succeed.")
        if self.scenario == "expired_artifact":
            raise MeshyTransportError("artifact_expired", "The mocked artifact URL has expired (expires_at is in the past).")

        source = FIXTURES_DIR / "mock_concept.stl"
        if not source.is_file():
            raise MeshyTransportError("artifact_missing", f"mock fixture STL not found at {source}")
        destination = Path(destination)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        return destination
