// nameplate.scad
// Raised-text nameplate generated by ai-3d-factory
// (factory generate-openscad --template nameplate).
// Single-color design: base plate and raised text are fused into one solid.
// For a multi-color version with separate aligned parts, use
// --template multipart-nameplate instead.

// ---- Parameters (all in millimeters) ----
plate_width = 90;
plate_depth = 30;
plate_height = 5;
text_string = "AI 3D Factory";
text_size = 10;
text_height = 2;      // how far the raised text rises above the plate surface
text_font = "Liberation Sans:style=Bold";  // change if this font isn't installed locally

module nameplate_base() {
    cube([plate_width, plate_depth, plate_height]);
}

module nameplate_text() {
    translate([plate_width / 2, plate_depth / 2, plate_height])
        linear_extrude(height = text_height)
            text(text_string, size = text_size, halign = "center", valign = "center", font = text_font);
}

union() {
    nameplate_base();
    nameplate_text();
}
